baseURL = 'https://TheTrafficNetwork.github.io/'
languageCode = 'en-us'
theme = 'anatole'
enableEmoji = true

[params]
title = 'Routing People and Packets'
author = 'TheTrafficNetwork'
description = 'These are the random musings of a traffic engineer in a networking role'
profilePicture = "images/Traffic-Lights-Exposure.jpg"